name: Release & Security Advisory

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    name: Create Release
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Validate script before release
        run: |
          bash -n EtherFang.sh
          shellcheck -x EtherFang.sh
      
      - name: Generate changelog
        id: changelog
        run: |
          PREV_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          if [ -z "$PREV_TAG" ]; then
            CHANGELOG=$(git log --oneline)
          else
            CHANGELOG=$(git log $PREV_TAG..HEAD --oneline)
          fi
          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          echo "$CHANGELOG" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: EtherFang ${{ github.ref_name }}
          body: |
            ## Changes
            ${{ env.CHANGELOG }}
            
            ## Security Notice
            Please review SECURITY.md for vulnerability reporting procedures.
            
            ## Legal Notice
            By using EtherFang, you agree to the terms outlined in SECURITY.md. Unauthorized network access is illegal.
          draft: false
          prerelease: false
